# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rainbondVersion: v5.2.0-cloud

## Install Default RBAC roles and bindings
rbac:
  create: true
  apiVersion: v1

## Service account name and whether to create it
serviceAccount:
  create: true
  name:

enableEtcdOperator: false
enableMySQLOperator: false

# rainbondOperator
rainbondOperator:
  name: rainbond-operator
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond-operator
    tag: v1.0.0-cloud
    pullPolicy: IfNotPresent
  regionDBName: region

# openapi
openapi:
  name: openapi
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-op-ui
    tag: v1.0.0-cloud
    pullPolicy: IfNotPresent
  port: 8080
  nodePort: 30008
  downloadURL: https://rainbond-pkg.oss-cn-shanghai.aliyuncs.com/offline/5.2/rainbond.images.2020-03-25-V5.2.0-beta2.tgz
  downloadMD5: 0b97553a9dd54c6ecafcfbd851df79cf45085eca060dbd0e6a8fd3682ac6e8a3
  installMode: WithoutPackage
  imageRepository: registry.cn-hangzhou.aliyuncs.com/goodrain
  onlyRegion: true
