apiVersion: rainbond.io/v1alpha1
kind: RbdComponent
metadata:
  name: metrics-server
  namespace: rbd-system
  labels:
    belongTo: rainbond-operator
    creator: Rainbond
    name: metrics-server
spec:
  replicas: 1
  image: registry.cn-hangzhou.aliyuncs.com/goodrain/metrics-server:v0.3.6
  imagePullPolicy: IfNotPresent
  priorityComponent: false
