apiVersion: rainbond.io/v1alpha1
kind: RbdComponent
metadata:
  name: rbd-db
  namespace: rbd-system
  labels:
    belongTo: rainbond-operator
    creator: Rainbond
    name: rbd-db
spec:
  replicas: 1
  image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-db:8.0.19
  imagePullPolicy: IfNotPresent
  priorityComponent: false
